
//Script for a Houston Chronicle applicaton that shows high-water rescues calls hour by hour during the late August 2017 storm Hurricane Harvey.   

var map,nextStore=0,year=0,month=1,colors=[],unlock=!1,running=!1;
function initialize(){var a={zoom:12,center:new google.maps.LatLng(29.679347013389883,-95.49067497253418),mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:!1,backgroundColor:"white",zoomControl:!1,streetViewControl:!1,panControl:!1,gestureHandling:"none",keyboardShortcuts:!1,styles:[{elementType:"geometry",stylers:[{color:"#212121"}]},{elementType:"labels.icon",stylers:[{visibility:"off"}]},{elementType:"labels.text.fill",stylers:[{color:"#757575"}]},{elementType:"labels.text.stroke",stylers:[{color:"#212121"}]},
{featureType:"administrative",elementType:"geometry",stylers:[{color:"#757575"}]},{featureType:"administrative.country",elementType:"labels.text.fill",stylers:[{color:"#9e9e9e"}]},{featureType:"administrative.land_parcel",stylers:[{visibility:"off"}]},{featureType:"administrative.locality",elementType:"labels.text.fill",stylers:[{color:"#bdbdbd"}]},{featureType:"poi",elementType:"labels.text.fill",stylers:[{color:"#757575"}]},{featureType:"poi.park",elementType:"geometry",stylers:[{color:"#181818"}]},
{featureType:"poi.park",elementType:"labels.text.fill",stylers:[{color:"#616161"}]},{featureType:"poi.park",elementType:"labels.text.stroke",stylers:[{color:"#1b1b1b"}]},{featureType:"road",elementType:"geometry.fill",stylers:[{color:"#2c2c2c"}]},{featureType:"road",elementType:"labels.text.fill",stylers:[{color:"#8a8a8a"}]},{featureType:"road.arterial",elementType:"geometry",stylers:[{color:"#373737"}]},{featureType:"road.highway",elementType:"geometry",stylers:[{color:"#3c3c3c"}]},{featureType:"road.highway.controlled_access",
elementType:"geometry",stylers:[{color:"#4e4e4e"}]},{featureType:"road.local",elementType:"labels.text.fill",stylers:[{color:"#616161"}]},{featureType:"transit",elementType:"labels.text.fill",stylers:[{color:"#757575"}]},{featureType:"water",elementType:"geometry",stylers:[{color:"#000000"}]},{featureType:"water",elementType:"labels.text.fill",stylers:[{color:"#3d3d3d"}]}]};map=new google.maps.Map(document.getElementById("map"),a);fillColorArray();map.controls[google.maps.ControlPosition.TOP_LEFT].push(document.getElementById("Buttons"));
map.controls[google.maps.ControlPosition.TOP_RIGHT].push(document.getElementById("twitter"));map.controls[google.maps.ControlPosition.RIGHT_CENTER].push(document.getElementById("msg"));google.maps.event.addListener(map,"tilesloaded",function(){unlock=!0});layer_0=new google.maps.FusionTablesLayer({query:{select:"col7",from:"1YWYCzVB4eRYZyDxzHFVp3osbpVlh0PclYhnKOSeD"},map:map,styleId:2,templateId:2,clickable:!1});layer_2=new google.maps.FusionTablesLayer({query:{select:"col14",from:"1UDjl9K2mpemewrTU7T_q3naaCw_xX5hfkBBifbqA"},
map:null,styleId:2,templateId:2});layer_3=new google.maps.FusionTablesLayer({query:{select:"col20",from:"1hwPVKj2gXjplqgwmkgoY1-ZDFWMvgT210SVlXj6R",where:" col12 in ('100-year floodplain', '100-year floodplain with Overflow', '100-year floodplain with elevation', 'FLOODWAY')"},map:null,styleId:2,templateId:2,suppressInfowindows:!0,clickable:!1})}
function start(){unlock&&!running&&(document.getElementById("lightbox").style.display="none",document.getElementById("msg").style.display="none",running=!0,nextMonth())}function stop(){document.getElementById("lightbox").style.display="block";document.getElementById("msg").style.display="block";running=!1}
function nextMonth(){if(running){for(;stores[nextStore].date[1]<=year&&stores[nextStore].date[2]<=month;)addStore(stores[nextStore].coords,year,month),nextStore++;updateColors(year,month);nextStore<stores.length&&(59==month?(month=1,year++,document.getElementById("year").innerHTML=year):(month++,document.getElementById("month").innerHTML=month),setTimeout(nextMonth,50))}}for(var markersByMonth=[],i=0;59>i;++i)markersByMonth.push([]);
function updateColors(a,d){for(var e=markersByMonth[d-1],c=0,f=e.length;c<f;++c){var h=e[c],k=a-h.year;k%2&&(h.get("icon").fillColor=colors[k],h.notify("icon"))}}
function addStore(a,d,e){var c=new google.maps.LatLng(a[0],a[1]);a=new google.maps.Marker({position:c,clickable:!1,icon:{path:google.maps.SymbolPath.CIRCLE,fillOpacity:.1,fillColor:colors[0],strokeColor:colors[0],scale:0},optimized:!1,zIndex:d,map:null});c=new google.maps.Marker({position:c,clickable:!1,icon:{path:google.maps.SymbolPath.CIRCLE,fillOpacity:1,fillColor:colors[0],strokeWeight:0,scale:0},optimized:!1,zIndex:d});c.year=d;markersByMonth[e-1].push(c);for(d=0;10>=d;d++)setTimeout(setScale(c,
a,d/10),150*d)}function setScale(a,d,e){return function(){if(1==e)d.setMap(null);else{var c=d.get("icon");c.strokeOpacity=Math.cos(Math.PI/2*e);c.fillOpacity=.1*c.strokeOpacity;c.scale=10*Math.sin(Math.PI/2*e);d.set("icon",c);var f=a.get("icon");c=2>c.scale?0:2;f.scale!=c&&(f.scale=c,a.set("icon",f),a.getMap()||a.setMap(map))}}}
function fillColorArray(){for(var a=0;44>a;a++)11>a?(r=198,g=Math.floor(18*a),b=0):22>a?(r=Math.floor(18*(22-a)),g=198,b=0):33>a?(r=0,g=198,b=Math.floor(18*(a-22))):(r=0,g=Math.floor(18*(44-a)),b=198),colors[a]="rgb("+r+","+g+","+b+")"}function toggleLayer(a){a.getMap()?a.setMap(null):a.setMap(map)};
